name: Auto-deploy

on:
  push:
    branches:
      - master

jobs:
  launch_commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    #- name: Install cURL
    #  run: sudo apt-get update && sudo apt-get install -y curl

    - name: Login to Semaphore
      run: |
        curl -X POST -d "{\"auth\": \"ci\", \"password\": \"$ANSIBLE_PASSWORD\"}" -c cookies.txt https://semaphore.mubelotix.xyz/api/auth/login -v

    - name: Launch Task on Semaphore
      run: |
        curl -X POST -b cookies.txt -d '{"template_id": 24}' https://semaphore.mubelotix.xyz/api/project/1/tasks -v
